name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: docker build -t myimage . && docker run -v $PWD:/data myimage
    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: wslbridge2-backend
        path: wslbridge2-backend

